ALTER TABLE rooms ADD COLUMN host_port INTEGER;
ALTER TABLE rooms ADD COLUMN status TEXT NOT NULL DEFAULT 'waiting';
ALTER TABLE rooms ADD COLUMN current_player_count INTEGER NOT NULL DEFAULT 1;
ALTER TABLE rooms ADD COLUMN passphrase TEXT;
